### ISSUE TITLE
Networking error in vm startup on vmware_fusion

### ISSUE THREAD

**Issue by stevepereira** [hashicorp/photon-vagrant#4]
Not sure if this appears on vmware_workstation but I see this message starting the VM. I still have connectivity out from the machine and ssh in though.

```
...
==> default: Forwarding ports...
    default: -- 80 => 80
    default: -- 22 => 2222
==> default: Configuring network adapters within the VM...
Vagrant attempted to execute the capability 'configure_networks'
on the detect guest OS 'linux', but the guest doesn't
support that capability. This capability is required for your
configuration of Vagrant. Please either reconfigure Vagrant to
avoid this capability or fix the issue by creating the capability.
```

**Comment by KFishner** [comment]
This is a known issue but doesn't affect functionality. It's addressed in the blog post:
https://hashicorp.com/blog/vagrant-vmware-photon.html
"Note: If you see an error regarding "configure_networks", it can be ignored."

Thanks!

**Comment by stevepereira** [comment]
Whoops missed that - thanks!

**Comment by frapposelli** [comment]
There is also a plugin to add guests support for photon available here: https://github.com/vmware/vagrant-guests-photon

Also, a PR against Vagrant is in the works.
