### ISSUE TITLE
Docker commands fail on permission/TLS issue

### ISSUE THREAD

**Issue by stevepereira** [hashicorp/photon-vagrant#5]
From inside the VM:

```
vagrant [ ~ ]$ docker run -d -p 80:80 tutum/apache-php
FATA[0000] Post http:///var/run/docker.sock/v1.17/containers/create: dial unix /var/run/docker.sock: permission denied. Are you trying to connect to a TLS-enabled daemon without TLS?
vagrant [ ~ ]$ docker info
FATA[0000] Get http:///var/run/docker.sock/v1.17/info: dial unix /var/run/docker.sock: permission denied. Are you trying to connect to a TLS-enabled daemon without TLS?

```

**Comment by KFishner** [comment]
if you run with `sudo` it will work - tracking this issue here:
https://github.com/hashicorp/photon-vagrant/issues/3

**Comment by DinisCruz** [comment]
I just had the same issue inside the default Google Container Engine where via ssh the `docker` command needs to be executed using `sudo`

**Comment by KFishner** [comment]
@DinisCruz are you running the VMware Photon box on GCE?

**Comment by DinisCruz** [comment]
that was on the vm instances created by GCE by the 'Google Container Engine'

**Comment by frapposelli** [comment]
@DinisCruz are you using Vagrant to run Photon on GCE? or is that completely unrelated to Vagrant?

**Comment by DinisCruz** [comment]
I was not using Photon , just hit the same error on docker in GCE

**Comment by ccerrato147** [comment]
I fixed my issue by adding my user to the docker group and then logout/login

**Comment by ElijahLynn** [comment]
Thanks @ccerrato147, that works around that issue for on Ubuntu 14.04.
